const {MessageEmbed} = require("discord.js")

module.exports = {
	name: "poll",
	category: "utils",
	permissions: ["SEND_MESSAGES"],
	ownerOnly: false,
	usage: "poll [question]",
	examples: ["poll Should I slack ?"],
	description: "Create a poll.",
	async run(client, message, args) {
		if (!args[0]) return message.reply("Please enter a poll question")

		const embed = new MessageEmbed()
			.setTitle("Poll")
			.setColor("#00a3b5")
			.setDescription(args.slice(0).join(" "))
			.setTimestamp()
			.setFooter({text: `New poll generated by ${message.author.tag}`})
		
		const poll = await message.reply({embeds: [embed]})
		poll.react("✔")
		poll.react("❌")
	},
	options: [
		{
			name: "title",
			description: "Enter poll title",
			type: "STRING",
			required: true,
		},
		{
			name: "content",
			description: "Enter poll question",
			type: "STRING",
			required: true,
		}
	],
	async runInteraction(client, interaction) {
		const pollTitle = interaction.options.getString("title")
		const pollContent = interaction.options.getString("content")

		const embed = new MessageEmbed()
			.setTitle(pollTitle)
			.setColor("#00a3b5")
			.setDescription(pollContent)
			.setTimestamp()
			.setFooter({text: `New poll generated by ${interaction.user.tag}`})
		
		const poll = await interaction.reply({embeds: [embed], fetchReply: true})
		poll.react("✔")
		poll.react("❌")
	}
}